### ISSUE TITLE
Functions are not created

### ISSUE THREAD

**Issue by kszicsillag** [MicrosoftDocs/mslearn-apim-and-functions#2]
Running [/setup.sh](../blob/master/setup.sh) reports success, the functions apps and other resources are created, but the actual functions are missing. Linking [the log](https://gist.github.com/kszicsillag/8e847424cac3143ae680918707918566).

Empty function list in Azure portal:
![apim-missing-function](https://user-images.githubusercontent.com/1849897/69914483-664f6680-1445-11ea-9a32-2ddd4b2677d6.png)

Kudu's ZipDeployUI showing the contents of `wwwroot`:
![apim-kudu](https://user-images.githubusercontent.com/1849897/69914504-939c1480-1445-11ea-9c91-fcc0636d0355.png)

**Comment by ghost** [comment]
Wasted a tonne of time on this because of this issue.

**Comment by tristanwilkinson** [comment]
I was able to work around this problem by replacing the original zip files in this project with ones containing a subset of their contents. Specifically, only including the files beneath `bin/Debug/netcoreapp2.1` in each. (To be clear, using that location as the root for the new zip files, not deleting everything outside that location.)

**Comment by hunglv51** [comment]
> I was able to work around this problem by replacing the original zip files in this project with ones containing a subset of their contents. Specifically, only including the files beneath `bin/Debug/netcoreapp2.1` in each. (To be clear, using that location as the root for the new zip files, not deleting everything outside that location.)

I have tried but your solutions not working. So I unzip and create functions manually.

**Comment by alanchn31** [comment]
Concur with hunglv51. I had to unzip in my console. Then cd into the respective folders and run: `func azure functionapp publish [FUNCTIONAPPNAME]`

**Comment by nschoenberg** [comment]
I've the same Problem

**Comment by cpatel22** [comment]
I have same issue

**Comment by nschoenberg** [comment]
The recent [commit ](https://github.com/MicrosoftDocs/mslearn-apim-and-functions/commit/303f0b38cef8d690dd5cca98f4c9b3e0cdc129e4) to setup.sh fixed this issue for me, thanks!

**Comment by nickwalkmsft** [comment]
Thanks for reporting, and for your patience on a fix.
